.TH "src/anyoption.h" 3 "Wed May 25 2016" "Version 2.0" "Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/anyoption.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstring>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnyOption\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOMMON_OPT\fP   1"
.br
.ti -1c
.RI "#define \fBCOMMAND_OPT\fP   2"
.br
.ti -1c
.RI "#define \fBFILE_OPT\fP   3"
.br
.ti -1c
.RI "#define \fBCOMMON_FLAG\fP   4"
.br
.ti -1c
.RI "#define \fBCOMMAND_FLAG\fP   5"
.br
.ti -1c
.RI "#define \fBFILE_FLAG\fP   6"
.br
.ti -1c
.RI "#define \fBCOMMAND_OPTION_TYPE\fP   1"
.br
.ti -1c
.RI "#define \fBCOMMAND_FLAG_TYPE\fP   2"
.br
.ti -1c
.RI "#define \fBFILE_OPTION_TYPE\fP   3"
.br
.ti -1c
.RI "#define \fBFILE_FLAG_TYPE\fP   4"
.br
.ti -1c
.RI "#define \fBUNKNOWN_TYPE\fP   5"
.br
.ti -1c
.RI "#define \fBDEFAULT_MAXOPTS\fP   10"
.br
.ti -1c
.RI "#define \fBMAX_LONG_PREFIX_LENGTH\fP   2"
.br
.ti -1c
.RI "#define \fBDEFAULT_MAXUSAGE\fP   3"
.br
.ti -1c
.RI "#define \fBDEFAULT_MAXHELP\fP   10"
.br
.ti -1c
.RI "#define \fBTRUE_FLAG\fP   'true'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COMMAND_FLAG   5"

.SS "#define COMMAND_FLAG_TYPE   2"

.SS "#define COMMAND_OPT   2"

.SS "#define COMMAND_OPTION_TYPE   1"

.SS "#define COMMON_FLAG   4"

.SS "#define COMMON_OPT   1"

.SS "#define DEFAULT_MAXHELP   10"

.SS "#define DEFAULT_MAXOPTS   10"

.SS "#define DEFAULT_MAXUSAGE   3"

.SS "#define FILE_FLAG   6"

.SS "#define FILE_FLAG_TYPE   4"

.SS "#define FILE_OPT   3"

.SS "#define FILE_OPTION_TYPE   3"

.SS "#define MAX_LONG_PREFIX_LENGTH   2"

.SS "#define TRUE_FLAG   'true'"

.SS "#define UNKNOWN_TYPE   5"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sequencer from the source code\&.
