.TH "Arguments" 3 "Wed May 25 2016" "Version 2.0" "Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arguments \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Arguments\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArguments\fP (int argCount, char *argVector[])"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAnyOption\fP * \fBoptions\fP"
.br
.ti -1c
.RI "string \fBinputFile\fP"
.br
.ti -1c
.RI "string \fBoutputFile\fP"
.br
.ti -1c
.RI "bool \fBinputFileDefined\fP"
.br
.ti -1c
.RI "bool \fBoutputFileDefined\fP"
.br
.ti -1c
.RI "bool \fBhelpFlag\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Arguments::Arguments (intargCount, char *argVector[])\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool Arguments::helpFlag"

.SS "string Arguments::inputFile"

.SS "bool Arguments::inputFileDefined"

.SS "\fBAnyOption\fP* Arguments::options"

.SS "string Arguments::outputFile"

.SS "bool Arguments::outputFileDefined"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sequencer from the source code\&.
