.TH "src/main.cpp" 3 "Wed May 25 2016" "Version 2.0" "Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <istream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'StringPair\&.h'\fP
.br
\fC#include 'SegmentSet\&.h'\fP
.br
\fC#include 'Arguments\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsequencer\fP (\fBArguments\fP *arguments)"
.br
.ti -1c
.RI "int \fBmain\fP (int argCount, char *argVector[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargCount, char *argVector[])"

.SS "void sequencer (\fBArguments\fP *arguments)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sequencer from the source code\&.
