.TH "MergeTest" 3 "Wed May 25 2016" "Version 2.0" "Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MergeTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBa\fP"
.br
.ti -1c
.RI "string \fBb\fP"
.br
.ti -1c
.RI "bool \fBforcemerge\fP"
.br
.ti -1c
.RI "string \fBexpectedResult\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string MergeTest::a"

.SS "string MergeTest::b"

.SS "string MergeTest::expectedResult"

.SS "bool MergeTest::forcemerge"

.SS "string MergeTest::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sequencer from the source code\&.
