.TH "ProcessTest" 3 "Wed May 25 2016" "Version 2.0" "Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProcessTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< string > \fBtestSegments\fP"
.br
.ti -1c
.RI "string \fBexpectedResult\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string ProcessTest::expectedResult"

.SS "string ProcessTest::name"

.SS "vector<string> ProcessTest::testSegments"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sequencer from the source code\&.
