.TH "src/SegmentSet.h" 3 "Wed May 25 2016" "Version 2.0" "Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/SegmentSet.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'StringPair\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSegmentSet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Sequencer from the source code\&.
