.TH "src/SegmentSetTests.cpp" 3 "Wed May 25 2016" "Version 2.0" "Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/SegmentSetTests.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'SegmentSet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBProcessTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "vector< \fBProcessTest\fP > \fBgetTests\fP ()"
.br
.ti -1c
.RI "void \fBdoTests\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void doTests ()"

.SS "vector< \fBMergeTest\fP > getTests ()"

.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sequencer from the source code\&.
