.TH "src/SegmentSet.cpp" 3 "Wed May 25 2016" "Version 2.0" "Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/SegmentSet.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include <istream>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'StringPair\&.h'\fP
.br
\fC#include 'SegmentSet\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Sequencer from the source code\&.
