.TH "SegmentSet" 3 "Wed May 25 2016" "Version 2.0" "Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegmentSet \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SegmentSet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSegmentSet\fP (vector< string > newSegments)"
.br
.ti -1c
.RI "\fBSegmentSet\fP (istream *inputStream)"
.br
.ti -1c
.RI "\fBSegmentSet\fP ()"
.br
.ti -1c
.RI "int \fBnSegments\fP ()"
.br
.ti -1c
.RI "bool \fBprocess\fP ()"
.br
.ti -1c
.RI "string \fBgetResults\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< string > \fBsegments\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SegmentSet::SegmentSet (vector< string >newSegments)\fC [inline]\fP"

.SS "SegmentSet::SegmentSet (istream *inputStream)"

.SS "SegmentSet::SegmentSet ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "string SegmentSet::getResults ()"

.SS "int SegmentSet::nSegments ()\fC [inline]\fP"

.SS "bool SegmentSet::process ()"

.SH "Member Data Documentation"
.PP 
.SS "vector<string> SegmentSet::segments"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sequencer from the source code\&.
