.TH "src/StringMerge.cpp" 3 "Wed May 25 2016" "Version 2.0" "Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/StringMerge.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'StringPair\&.h'\fP
.br
\fC#include 'StringMerge\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Sequencer from the source code\&.
