.TH "StringPair" 3 "Wed May 25 2016" "Version 2.0" "Sequencer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringPair \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StringPair\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStringPair\fP ()"
.br
.ti -1c
.RI "\fBStringPair\fP (string a, string b)"
.br
.ti -1c
.RI "string \fBprintPair\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBmergePair\fP (\fBStringPair\fP a, int module, bool initial)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBx\fP"
.br
.ti -1c
.RI "string \fBy\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StringPair::StringPair ()"

.SS "StringPair::StringPair (stringa, stringb)"

.SH "Member Function Documentation"
.PP 
.SS "string StringPair::mergePair (\fBStringPair\fPa, intmodule, boolinitial)\fC [static]\fP"

.SS "string StringPair::printPair ()"

.SH "Member Data Documentation"
.PP 
.SS "string StringPair::x"

.SS "string StringPair::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sequencer from the source code\&.
